name: Multiple premoves debug APK

on: [push]

permissions: read-all

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin
      - name: Checkout mobile code
        uses: actions/checkout@v7.0.1
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.0'
          channel: stable
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Code generation
        run: dart run build_runner build
      - name: Build debug APK
        run: flutter build apk --debug
      - name: Upload debug APK
        uses: actions/upload-artifact@v7
        with:
          name: lichess-multiple-premoves-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          if-no-files-found: error
          retention-days: 7
